[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "xgboostlss"

version = "0.1.7"

description = "XGBoostLSS - An extension of XGBoost to probabilistic forecasting"
authors = [
    "Alexander März <alex.maerz@gmx.net>",
]
maintainers = [
    "Alexander März <alex.maerz@gmx.net>",
    "Sebastian Cattes <sebastian.cattes@inwt-statistics.de>",
]
license = "Apache License 2.0"

readme = "README.md"

packages = [
    { include = "xgboostlss", from = "." }
]


homepage = "https://github.com/StatMixedML/XGBoostLSS"
repository = "https://github.com/StatMixedML/XGBoostLSS"
documentation = "https://github.com/StatMixedML/XGBoostLSS"

keywords = ["xgboost", "xgboostlss"]

classifiers = [
            'Development Status :: 3 - Alpha',
            'Intended Audience :: Developers',
            'License :: OSI Approved :: Apache Software License',
            "Operating System :: OS Independent",
            'Programming Language :: Python :: 3',
            'Programming Language :: Python :: 3.7',
            'Programming Language :: Python :: 3.8',
            'Programming Language :: Python :: 3.9',
            "Programming Language :: Python :: 3.10",
            'Programming Language :: Python :: 3 :: Only',
            ]

[tool.poetry.build]
generate-setup-file = true

# Requirements
[tool.poetry.dependencies]
python = ">=3.9"

xgboost = "^1.7.5"
torch = { version = "^2.0.1+cpu", source = "torchcpu" }
optuna = "^3.1.1"
properscoring= "^0.1"
scikit-learn = "^1.2.2"
numpy = "^1.24.3"
pandas = "^2.0.1"
plotnine = "^0.12.1"
scipy = "^1.9.3"
tqdm = "^4.65.0"
matplotlib = "^3.7.1"
shap = { git = "ssh://git@github.com/dsgibbons/shap.git", branch = "master" }

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
atomicwrites = "^1.4.1"
matplotlib = "^3.5.2"
ipywidgets = "^7.7.1"
ipython = "^7.23.1"
bump2version = "^1.0.1"


[[tool.poetry.source]]
name = "torchcpu"
url = "https://download.pytorch.org/whl/cpu"
priority = 'explicit'
