[tool.poetry]
name = "xgboostlss"
version = "0.1.0"
description = "XGBoostLSS - An extension of XGBoost to probabilistic forecasting"
authors = ["Alexander März"]
repository = "https://github.com/StatMixedML/XGBoostLSS"
readme = "README.md"
license = "Apache License 2.0"
keywords = ["XGBoost", "distributional-regression", "Machine Learning"]
classifiers = [
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "^3.7"
xgboost = "^1.4.2"
optuna = "^2.9.1"
scikit-learn = "^0.24.2"
scipy = "^1.7.1"
shap = "^0.39.0"
matplotlib = "^3.4.3"
tqdm = "^4.62.2"


[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
